name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO_VERSION: stable

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        run: go test -race ./...
  s3-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout awsig
        uses: actions/checkout@v5
        with:
          path: awsig
      - name: Checkout s3-tests
        uses: actions/checkout@v5
        with:
          repository: amwolff/s3-tests
          ref: mark-failing-auth-tests-fails_on_aws
          path: s3-tests
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Install tox
        run: sudo apt update && sudo apt install tox
      - name: Run s3-tests
        run: |
          go run -C awsig/cmd/s3tests/ . &
          SERVER_PID=$!
          S3TEST_CONF=s3tests.conf.SAMPLE tox -c s3-tests/ -- -m '(auth_aws2 or auth_aws4 or auth_common) and not fails_on_aws'
          kill $SERVER_PID
